name: progressive_button_flutter
description: "A customizable Flutter button widget with built-in loading and progress indicators."
version: 1.2.0
homepage: https://github.com/Penguin5681/Progressive-Button-Flutter

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.43

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
